### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by laraalinas** [michaelmunz/H5PTranslator#2]
Translation of two course presentations (H5P) performed, then the tool stopped working.
An output file is generated, but the content is still English.
The following error message is shown:
![image](https://user-images.githubusercontent.com/124900451/217842480-5c1d6d98-912d-4dd0-bf7f-3f2349557513.png)

Therefore, further translations cannot be performed at this point in time by UASTW.

Additionally, the interactive elements "fill the blanks" and "True-False" in the H5P course presentations are not translated.

**Comment by michaelmunz** [comment]
Dear lara, 
could you please attach the corresponding H5P file here so that I can reproduce the issue?
Thanks and regards,
Michael

**Comment by laraalinas** [comment]
Files have been sent via E-Mail.

**Comment by michaelmunz** [comment]
Issue has been solved in release v0.9.2
