### ISSUE TITLE
Issue with transformation_of_signals.h5p

### ISSUE THREAD

**Issue by csekorichard** [michaelmunz/H5PTranslator#3]
Dear Michael!
I have received the following error when translating the Transformation of Signals course. Checking the output file, the translation worked fine up until the end of the 23rd slide of 31, where the first True/False question is located. I have attached the .h5p and the error message to this issue in a .zip (because bare .h5p is blocked).
[error_ToS.zip](https://github.com/michaelmunz/H5PTranslator/files/10720921/error_ToS.zip)
Thanks
Richard

**Comment by michaelmunz** [comment]
Dear Richard,
I cannot reproduce the issue with the current version: I translated it without any problem.
Are you sure that you have used the latest version?
The translated version also looks fine besides the fact that the True/False Buttons are not translated. But this should be handled inside Moodle, as soon as you upload it and select the correct internationalisation. (please inform me if not).

Greetings,
Michael

**Comment by michaelmunz** [comment]
Reopened. Issue can be reproduced with hungarian translation only

**Comment by michaelmunz** [comment]
Issue is solved in release v0.9.3
