### ISSUE TITLE
Translation not working issue (continued)

### ISSUE THREAD

**Issue by laraalinas** [michaelmunz/H5PTranslator#4]
Using the new release (v0.9.2) translation of Module 3 to German worked, however when translating to Hungarian the progress bar stops about halfway through translating and the following error message is shown: 

![image](https://user-images.githubusercontent.com/124900451/218475232-c30d4bf1-c37d-4e67-8b67-fc4aa0db7201.png)
![image](https://user-images.githubusercontent.com/124900451/218475292-d72433df-72cd-4b74-b8d5-d50c0992fea6.png)

**Comment by laraalinas** [comment]
When translating module 4 from English to German or Hungarian the following error message is shown:
![image](https://user-images.githubusercontent.com/124900451/218476135-512f4017-5458-44ae-b4ba-067baeed338c.png)

**Comment by laraalinas** [comment]
Translating module 6 to German works, however, translating to hungarian leads to the following error:
![image](https://user-images.githubusercontent.com/124900451/218477878-d2301ad2-b828-4f92-a1ba-40ba4f0e03a7.png)

**Comment by laraalinas** [comment]
Translating module 7 to German works, however, translating to hungarian leads to the identical error message as above

**Comment by michaelmunz** [comment]
Issue is solved in release v0.9.3
